/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as TeamSlugIndexRouteImport } from './routes/team.$slug.index'
import { Route as TeamSlugProductRouteImport } from './routes/team.$slug.$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugIndexRoute = TeamSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamSlugRoute,
} as any)
const TeamSlugProductRoute = TeamSlugProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => TeamSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/team/$slug': typeof TeamSlugRouteWithChildren
  '/team/': typeof TeamIndexRoute
  '/team/$slug/$product': typeof TeamSlugProductRoute
  '/team/$slug/': typeof TeamSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/team': typeof TeamIndexRoute
  '/team/$slug/$product': typeof TeamSlugProductRoute
  '/team/$slug': typeof TeamSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/team/$slug': typeof TeamSlugRouteWithChildren
  '/team/': typeof TeamIndexRoute
  '/team/$slug/$product': typeof TeamSlugProductRoute
  '/team/$slug/': typeof TeamSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/team/$slug' | '/team/' | '/team/$slug/$product' | '/team/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/team' | '/team/$slug/$product' | '/team/$slug'
  id:
    | '__root__'
    | '/'
    | '/team/$slug'
    | '/team/'
    | '/team/$slug/$product'
    | '/team/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamSlugRoute: typeof TeamSlugRouteWithChildren
  TeamIndexRoute: typeof TeamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug/': {
      id: '/team/$slug/'
      path: '/'
      fullPath: '/team/$slug/'
      preLoaderRoute: typeof TeamSlugIndexRouteImport
      parentRoute: typeof TeamSlugRoute
    }
    '/team/$slug/$product': {
      id: '/team/$slug/$product'
      path: '/$product'
      fullPath: '/team/$slug/$product'
      preLoaderRoute: typeof TeamSlugProductRouteImport
      parentRoute: typeof TeamSlugRoute
    }
  }
}

interface TeamSlugRouteChildren {
  TeamSlugProductRoute: typeof TeamSlugProductRoute
  TeamSlugIndexRoute: typeof TeamSlugIndexRoute
}

const TeamSlugRouteChildren: TeamSlugRouteChildren = {
  TeamSlugProductRoute: TeamSlugProductRoute,
  TeamSlugIndexRoute: TeamSlugIndexRoute,
}

const TeamSlugRouteWithChildren = TeamSlugRoute._addFileChildren(
  TeamSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamSlugRoute: TeamSlugRouteWithChildren,
  TeamIndexRoute: TeamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
