/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreorderRouteImport } from './routes/preorder'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as TeamSlugIndexRouteImport } from './routes/team.$slug.index'
import { Route as TeamSlugProductRouteImport } from './routes/team.$slug.$product'
import { Route as TeamSlugAlumniRouteImport } from './routes/team.$slug.alumni'
import { Route as TeamSlugMatchRouteImport } from './routes/team.$slug.match'
import { Route as TeamSlugSidelineRouteImport } from './routes/team.$slug.sideline'
import { Route as TeamSlugWarmupsRouteImport } from './routes/team.$slug.warmups'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreorderRoute = PreorderRouteImport.update({
  id: '/preorder',
  path: '/preorder',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugIndexRoute = TeamSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamSlugRoute,
} as any)
const TeamSlugProductRoute = TeamSlugProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => TeamSlugRoute,
} as any)
const TeamSlugAlumniRoute = TeamSlugAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => TeamSlugRoute,
} as any)
const TeamSlugMatchRoute = TeamSlugMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => TeamSlugRoute,
} as any)
const TeamSlugSidelineRoute = TeamSlugSidelineRouteImport.update({
  id: '/sideline',
  path: '/sideline',
  getParentRoute: () => TeamSlugRoute,
} as any)
const TeamSlugWarmupsRoute = TeamSlugWarmupsRouteImport.update({
  id: '/warmups',
  path: '/warmups',
  getParentRoute: () => TeamSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preorder': typeof PreorderRoute
  '/team/$slug': typeof TeamSlugRouteWithChildren
  '/team/': typeof TeamIndexRoute
  '/team/$slug/$product': typeof TeamSlugProductRoute
  '/team/$slug/alumni': typeof TeamSlugAlumniRoute
  '/team/$slug/match': typeof TeamSlugMatchRoute
  '/team/$slug/sideline': typeof TeamSlugSidelineRoute
  '/team/$slug/warmups': typeof TeamSlugWarmupsRoute
  '/team/$slug/': typeof TeamSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preorder': typeof PreorderRoute
  '/team': typeof TeamIndexRoute
  '/team/$slug/$product': typeof TeamSlugProductRoute
  '/team/$slug/alumni': typeof TeamSlugAlumniRoute
  '/team/$slug/match': typeof TeamSlugMatchRoute
  '/team/$slug/sideline': typeof TeamSlugSidelineRoute
  '/team/$slug/warmups': typeof TeamSlugWarmupsRoute
  '/team/$slug': typeof TeamSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preorder': typeof PreorderRoute
  '/team/$slug': typeof TeamSlugRouteWithChildren
  '/team/': typeof TeamIndexRoute
  '/team/$slug/$product': typeof TeamSlugProductRoute
  '/team/$slug/alumni': typeof TeamSlugAlumniRoute
  '/team/$slug/match': typeof TeamSlugMatchRoute
  '/team/$slug/sideline': typeof TeamSlugSidelineRoute
  '/team/$slug/warmups': typeof TeamSlugWarmupsRoute
  '/team/$slug/': typeof TeamSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preorder'
    | '/team/$slug'
    | '/team/'
    | '/team/$slug/$product'
    | '/team/$slug/alumni'
    | '/team/$slug/match'
    | '/team/$slug/sideline'
    | '/team/$slug/warmups'
    | '/team/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preorder'
    | '/team'
    | '/team/$slug/$product'
    | '/team/$slug/alumni'
    | '/team/$slug/match'
    | '/team/$slug/sideline'
    | '/team/$slug/warmups'
    | '/team/$slug'
  id:
    | '__root__'
    | '/'
    | '/preorder'
    | '/team/$slug'
    | '/team/'
    | '/team/$slug/$product'
    | '/team/$slug/alumni'
    | '/team/$slug/match'
    | '/team/$slug/sideline'
    | '/team/$slug/warmups'
    | '/team/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreorderRoute: typeof PreorderRoute
  TeamSlugRoute: typeof TeamSlugRouteWithChildren
  TeamIndexRoute: typeof TeamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preorder': {
      id: '/preorder'
      path: '/preorder'
      fullPath: '/preorder'
      preLoaderRoute: typeof PreorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug/': {
      id: '/team/$slug/'
      path: '/'
      fullPath: '/team/$slug/'
      preLoaderRoute: typeof TeamSlugIndexRouteImport
      parentRoute: typeof TeamSlugRoute
    }
    '/team/$slug/$product': {
      id: '/team/$slug/$product'
      path: '/$product'
      fullPath: '/team/$slug/$product'
      preLoaderRoute: typeof TeamSlugProductRouteImport
      parentRoute: typeof TeamSlugRoute
    }
    '/team/$slug/alumni': {
      id: '/team/$slug/alumni'
      path: '/alumni'
      fullPath: '/team/$slug/alumni'
      preLoaderRoute: typeof TeamSlugAlumniRouteImport
      parentRoute: typeof TeamSlugRoute
    }
    '/team/$slug/match': {
      id: '/team/$slug/match'
      path: '/match'
      fullPath: '/team/$slug/match'
      preLoaderRoute: typeof TeamSlugMatchRouteImport
      parentRoute: typeof TeamSlugRoute
    }
    '/team/$slug/sideline': {
      id: '/team/$slug/sideline'
      path: '/sideline'
      fullPath: '/team/$slug/sideline'
      preLoaderRoute: typeof TeamSlugSidelineRouteImport
      parentRoute: typeof TeamSlugRoute
    }
    '/team/$slug/warmups': {
      id: '/team/$slug/warmups'
      path: '/warmups'
      fullPath: '/team/$slug/warmups'
      preLoaderRoute: typeof TeamSlugWarmupsRouteImport
      parentRoute: typeof TeamSlugRoute
    }
  }
}

interface TeamSlugRouteChildren {
  TeamSlugProductRoute: typeof TeamSlugProductRoute
  TeamSlugAlumniRoute: typeof TeamSlugAlumniRoute
  TeamSlugMatchRoute: typeof TeamSlugMatchRoute
  TeamSlugSidelineRoute: typeof TeamSlugSidelineRoute
  TeamSlugWarmupsRoute: typeof TeamSlugWarmupsRoute
  TeamSlugIndexRoute: typeof TeamSlugIndexRoute
}

const TeamSlugRouteChildren: TeamSlugRouteChildren = {
  TeamSlugProductRoute: TeamSlugProductRoute,
  TeamSlugAlumniRoute: TeamSlugAlumniRoute,
  TeamSlugMatchRoute: TeamSlugMatchRoute,
  TeamSlugSidelineRoute: TeamSlugSidelineRoute,
  TeamSlugWarmupsRoute: TeamSlugWarmupsRoute,
  TeamSlugIndexRoute: TeamSlugIndexRoute,
}

const TeamSlugRouteWithChildren = TeamSlugRoute._addFileChildren(
  TeamSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreorderRoute: PreorderRoute,
  TeamSlugRoute: TeamSlugRouteWithChildren,
  TeamIndexRoute: TeamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
